package com.cn.model;

import java.util.Date;

public class CustomerDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_device.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    public CustomerDevice() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_device
     *
     * @mbggenerated
     */

    public CustomerDevice(String id, String customerId, String deviceId, String status, Date createDate) {
        this.id = id;
        this.customerId = customerId;
        this.deviceId = deviceId;
        this.status = status;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_device.id
     *
     * @return the value of t_customer_device.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_device.customer_id
     *
     * @return the value of t_customer_device.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_device.device_id
     *
     * @return the value of t_customer_device.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_device.status
     *
     * @return the value of t_customer_device.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_device.create_date
     *
     * @return the value of t_customer_device.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}