package com.cn.model;

public class CustomerMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_message.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_message.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_message.message_id
     *
     * @mbggenerated
     */
    private String messageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_message
     *
     * @mbggenerated
     */
    public CustomerMessage(String id, String customerId, String messageId) {
        this.id = id;
        this.customerId = customerId;
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_message.Id
     *
     * @return the value of t_customer_message.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_message.customer_id
     *
     * @return the value of t_customer_message.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_message.message_id
     *
     * @return the value of t_customer_message.message_id
     *
     * @mbggenerated
     */
    public String getMessageId() {
        return messageId;
    }
}