package com.cn.model;

import java.util.Date;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.feedback
     *
     * @mbggenerated
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.contact
     *
     * @mbggenerated
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.login_id
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.customer_Id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.deal_time
     *
     * @mbggenerated
     */
    private Date dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feedback.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_feedback
     *
     * @mbggenerated
     */
    public Feedback(String id, String feedback, String contact, String loginId, String customerId, String status, Date createTime, Date dealTime, String remark) {
        this.id = id;
        this.feedback = feedback;
        this.contact = contact;
        this.loginId = loginId;
        this.customerId = customerId;
        this.status = status;
        this.createTime = createTime;
        this.dealTime = dealTime;
        this.remark = remark;
    }

    public Feedback() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.Id
     *
     * @return the value of t_feedback.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.feedback
     *
     * @return the value of t_feedback.feedback
     *
     * @mbggenerated
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.contact
     *
     * @return the value of t_feedback.contact
     *
     * @mbggenerated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.login_id
     *
     * @return the value of t_feedback.login_id
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.customer_Id
     *
     * @return the value of t_feedback.customer_Id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.status
     *
     * @return the value of t_feedback.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.create_time
     *
     * @return the value of t_feedback.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.deal_time
     *
     * @return the value of t_feedback.deal_time
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feedback.remark
     *
     * @return the value of t_feedback.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}