package com.cn.model;

import java.util.Date;

public class Merchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.brief
     *
     * @mbggenerated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.lat
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.lon
     *
     * @mbggenerated
     */
    private String lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.remark
     *
     * @mbggenerated
     */
    private String status;
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated
     */
    public Merchant(String id, String name, String phone, String brief, String address, String lat, String lon, String status,String remark, Date createTime) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.brief = brief;
        this.address = address;
        this.lat = lat;
        this.lon = lon;
        this.status=status;
        this.remark = remark;
        this.createTime = createTime;
    }

    public Merchant() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.Id
     *
     * @return the value of t_merchant.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.name
     *
     * @return the value of t_merchant.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.phone
     *
     * @return the value of t_merchant.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.brief
     *
     * @return the value of t_merchant.brief
     *
     * @mbggenerated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.address
     *
     * @return the value of t_merchant.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.lat
     *
     * @return the value of t_merchant.lat
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.lon
     *
     * @return the value of t_merchant.lon
     *
     * @mbggenerated
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.remark
     *
     * @return the value of t_merchant.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.create_time
     *
     * @return the value of t_merchant.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setBrief(String brief) {
        this.brief = brief;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public void setLon(String lon) {
        this.lon = lon;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}