package com.cn.model;

public class Param {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.key
     *
     * @mbggenerated
     */
    private String kv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.remark
     *
     * @mbggenerated
     */
    private String remark;

    public Param() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbggenerated
     */

    public Param(String id, String kv, String name, String type, String value, Integer seq, String remark) {
        this.id = id;
        this.kv = kv;
        this.name = name;
        this.type = type;
        this.value = value;
        this.seq = seq;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.Id
     *
     * @return the value of t_param.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.key
     *
     * @return the value of t_param.key
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.name
     *
     * @return the value of t_param.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.type
     *
     * @return the value of t_param.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.value
     *
     * @return the value of t_param.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.seq
     *
     * @return the value of t_param.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.remark
     *
     * @return the value of t_param.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    public void setId(String id) {
        this.id = id;
    }



    public void setName(String name) {
        this.name = name;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getKv() {
        return kv;
    }

    public void setKv(String kv) {
        this.kv = kv;
    }
}