package com.cn.model;

import java.util.Date;

public class ScheduleJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.job_id
     *
     * @mbggenerated
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.job_name
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.job_group
     *
     * @mbggenerated
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.job_status
     *
     * @mbggenerated
     */
    private String jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.cron_expression
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.bean_class
     *
     * @mbggenerated
     */
    private String beanClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.is_concurrent
     *
     * @mbggenerated
     */
    private String isConcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.spring_id
     *
     * @mbggenerated
     */
    private String springId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_job.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_schedule_job
     *
     * @mbggenerated
     */
    public ScheduleJob(String jobId, Date createTime, Date updateTime, String jobName, String jobGroup, String jobStatus, String cronExpression, String description, String beanClass, String isConcurrent, String springId, String methodName) {
        this.jobId = jobId;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.jobName = jobName;
        this.jobGroup = jobGroup;
        this.jobStatus = jobStatus;
        this.cronExpression = cronExpression;
        this.description = description;
        this.beanClass = beanClass;
        this.isConcurrent = isConcurrent;
        this.springId = springId;
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.job_id
     *
     * @return the value of t_schedule_job.job_id
     *
     * @mbggenerated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.create_time
     *
     * @return the value of t_schedule_job.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.update_time
     *
     * @return the value of t_schedule_job.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.job_name
     *
     * @return the value of t_schedule_job.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.job_group
     *
     * @return the value of t_schedule_job.job_group
     *
     * @mbggenerated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.job_status
     *
     * @return the value of t_schedule_job.job_status
     *
     * @mbggenerated
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.cron_expression
     *
     * @return the value of t_schedule_job.cron_expression
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.description
     *
     * @return the value of t_schedule_job.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.bean_class
     *
     * @return the value of t_schedule_job.bean_class
     *
     * @mbggenerated
     */
    public String getBeanClass() {
        return beanClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.is_concurrent
     *
     * @return the value of t_schedule_job.is_concurrent
     *
     * @mbggenerated
     */
    public String getIsConcurrent() {
        return isConcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.spring_id
     *
     * @return the value of t_schedule_job.spring_id
     *
     * @mbggenerated
     */
    public String getSpringId() {
        return springId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_job.method_name
     *
     * @return the value of t_schedule_job.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }

    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setBeanClass(String beanClass) {
        this.beanClass = beanClass;
    }

    public void setIsConcurrent(String isConcurrent) {
        this.isConcurrent = isConcurrent;
    }

    public void setSpringId(String springId) {
        this.springId = springId;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public ScheduleJob() {
    }
}